/* Generated by seqc 0.1.0 for workflow "numbers".
 * This file is rebuilt whenever the workflow, its inputs, or the toolchain
 * change; edits made here are not kept. */

/* ---- Compiler-owned prelude ---- */
#include "seq_runtime.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int seq_step_1(seq_ctx *ctx);
int seq_step_2(seq_ctx *ctx);

/* ---- Step functions (model-written) ---- */
int seq_step_1(seq_ctx *ctx) {
  FILE *out = seq_output_open("numbers.txt", "w");
  if (out == NULL) {
    return seq_fail(ctx, "cannot create numbers.txt");
  }
  for (int i = 1; i <= 5; ++i) {
    fprintf(out, "%d\n", i);
  }
  if (fclose(out) != 0) {
    return seq_fail(ctx, "cannot write numbers.txt");
  }
  return 0;
}

int seq_step_2(seq_ctx *ctx) {
  FILE *in = seq_output_open("numbers.txt", "r");
  if (in == NULL) {
    return seq_fail(ctx, "cannot open numbers.txt");
  }
  long sum = 0;
  long value = 0;
  while (fscanf(in, "%ld", &value) == 1) {
    sum += value;
  }
  fclose(in);

  FILE *out = seq_output_open("total.txt", "w");
  if (out == NULL) {
    return seq_fail(ctx, "cannot create total.txt");
  }
  fprintf(out, "%ld\n", sum);
  if (fclose(out) != 0) {
    return seq_fail(ctx, "cannot write total.txt");
  }
  printf("sum=%ld\n", sum);
  return 0;
}
/* ---- Compiler-owned driver ---- */
#ifndef SEQ_NO_MAIN
static const seq_step_entry seq_steps[] = {
    {"make_numbers", seq_step_1},
    {"add_numbers", seq_step_2},
};

int main(void) {
  return seq_run(seq_steps, 2);
}
#endif /* SEQ_NO_MAIN */
