/* Generated by seqc 0.1.0 for workflow "numbers". */
#include <gtest/gtest.h>
#include <fstream>

extern "C" {
#include "seq_runtime.h"
int seq_step_1(seq_ctx *ctx);
int seq_step_2(seq_ctx *ctx);
}

TEST(Numbers, WritesFiveLines) {
  seq_ctx ctx;
  seq_ctx_init(&ctx);
  EXPECT_EQ(0, seq_step_1(&ctx));
}

TEST(Numbers, WritesTheSum) {
  seq_ctx ctx;
  seq_ctx_init(&ctx);
  EXPECT_EQ(0, seq_step_1(&ctx));
  EXPECT_EQ(0, seq_step_2(&ctx));
  std::ifstream total("total.txt");
  long value = 0;
  total >> value;
  EXPECT_EQ(15, value);
}
